[tools]
aws-cli = { version = "2", symlink_bins = "true" }
bat = "0"
crush = "0"
docker-cli = "29"
fd = "10"
flux2 = "2"
fzf = "0"
go = "1"
helm = "4"
k9s = "0"
kubectl = "1"
node = "25"
pulumi = "3"
ripgrep = "15"
rust = "1"
sops = "3"
terraform = "1"
trufflehog = "3"
uv = "0"
zoxide = "0"
