[tools]
aws-cli = { version = "2", symlink_bins = "true" }
bat = "0"
crush = "0"
docker-cli = "29"
fd = "10"
flux2 = "2"
fzf = "0"
go = "1"
"go:github.com/hashicorp/terraform-mcp-server/cmd/terraform-mcp-server" = "0"
"go:golang.org/x/tools/gopls" = "0"
helm = "3"
helm-ls = "0"
k9s = "0"
kubectl = "1"
node = "25"
"npm:@sveltejs/mcp" = "0"
"npm:@upstash/context7-mcp" = "2"
"npm:@vtsls/language-server" = "0"
"npm:bash-language-server" = "5"
"npm:svelte-language-server" = "0"
pulumi = "3"
ripgrep = "15"
ruff = "0"
rust = "1"
rust-analyzer = "2026"
shellcheck = "0"
sops = "3"
terraform = "1"
terraform-ls = "0"
trufflehog = "3"
uv = "0"
zoxide = "0"
