[settings]
experimental = true
auto_install = true
lockfile = true

[settings.npm]
package_manager = "bun"

[tools]
aws-cli = { version = "2.34.0", symlink_bins = "true" }
bat = "0.26.1"
bun = "1.3.9"
deno = "2.6.9"
docker-cli = "29.2.1"
dotnet = "10.0.103"
dotnet-core = "10.0.103"
fd = "10.3.0"
flux2 = "2.7.5"
fzf = "0.67.0"
gh = "2.86.0"
go = "1.26.0"
"go:github.com/awslabs/eks-node-viewer/cmd/eks-node-viewer" = "0.7.4"
"go:github.com/charmbracelet/crush" = "v0.46.1"
"go:github.com/hashicorp/terraform-mcp-server/cmd/terraform-mcp-server" = "0.4.0"
"go:golang.org/x/tools/gopls" = "0.21.1"
helm = "4.1.1"
helm-ls = "0.5.4"
java = "25.0.2"
k9s = "0.50.18"
kubectl = "1.35.1"
lazygit = "0.59.0"
mkcert = "1.4.4"
neovim = "0.11.6"
node = "25.6.1"
npm = "11.10.0"
"npm:@astrojs/language-server" = "2.16.3"
"npm:@slidev/cli" = "52.12.0"
"npm:@sveltejs/mcp" = "0.1.20"
"npm:@upstash/context7-mcp" = "2.1.1"
"npm:@vtsls/language-server" = "0.3.0"
"npm:bash-language-server" = "5.6.0"
"npm:svelte-language-server" = "0.17.25"
oh-my-posh = "29.3.0"
pnpm = "10.29.3"
pulumi = "3.220.0"
python = "3.14.3"
ripgrep = "15.1.0"
ruff = "0.15.1"
rust = "1.93.1"
rust-analyzer = "2026-02-09"
shellcheck = "0.11.0"
sops = "3.11.0"
terraform = "1.14.5"
terraform-ls = "0.38.4"
tmux = "3.6a"
trufflehog = "3.93.3"
uv = "0.10.2"
yarn = "4.12.0"
yq = "4.52.2"
zoxide = "0.9.9"
